version: "3.8"

services:

  backend:
    build: ./backend
    container_name: phes_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - phes-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: phes_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - phes-network
    restart: unless-stopped

networks:
  phes-network:
    driver: bridge
